 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/datos_apis", type: :request do
  
  # DatosApi. As you add validations to DatosApi, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DatosApi.create! valid_attributes
      get datos_apis_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      datos_api = DatosApi.create! valid_attributes
      get datos_api_url(datos_api)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_datos_api_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      datos_api = DatosApi.create! valid_attributes
      get edit_datos_api_url(datos_api)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DatosApi" do
        expect {
          post datos_apis_url, params: { datos_api: valid_attributes }
        }.to change(DatosApi, :count).by(1)
      end

      it "redirects to the created datos_api" do
        post datos_apis_url, params: { datos_api: valid_attributes }
        expect(response).to redirect_to(datos_api_url(DatosApi.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DatosApi" do
        expect {
          post datos_apis_url, params: { datos_api: invalid_attributes }
        }.to change(DatosApi, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post datos_apis_url, params: { datos_api: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested datos_api" do
        datos_api = DatosApi.create! valid_attributes
        patch datos_api_url(datos_api), params: { datos_api: new_attributes }
        datos_api.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the datos_api" do
        datos_api = DatosApi.create! valid_attributes
        patch datos_api_url(datos_api), params: { datos_api: new_attributes }
        datos_api.reload
        expect(response).to redirect_to(datos_api_url(datos_api))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        datos_api = DatosApi.create! valid_attributes
        patch datos_api_url(datos_api), params: { datos_api: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested datos_api" do
      datos_api = DatosApi.create! valid_attributes
      expect {
        delete datos_api_url(datos_api)
      }.to change(DatosApi, :count).by(-1)
    end

    it "redirects to the datos_apis list" do
      datos_api = DatosApi.create! valid_attributes
      delete datos_api_url(datos_api)
      expect(response).to redirect_to(datos_apis_url)
    end
  end
end
