require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sub_opciones", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SubOpcion. As you add validations to SubOpcion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SubOpcion.create! valid_attributes
      get sub_opciones_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sub_opcion = SubOpcion.create! valid_attributes
      get sub_opcion_url(sub_opcion)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sub_opcion_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      sub_opcion = SubOpcion.create! valid_attributes
      get edit_sub_opcion_url(sub_opcion)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SubOpcion" do
        expect {
          post sub_opciones_url, params: { sub_opcion: valid_attributes }
        }.to change(SubOpcion, :count).by(1)
      end

      it "redirects to the created sub_opcion" do
        post sub_opciones_url, params: { sub_opcion: valid_attributes }
        expect(response).to redirect_to(sub_opcion_url(SubOpcion.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SubOpcion" do
        expect {
          post sub_opciones_url, params: { sub_opcion: invalid_attributes }
        }.to change(SubOpcion, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post sub_opciones_url, params: { sub_opcion: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sub_opcion" do
        sub_opcion = SubOpcion.create! valid_attributes
        patch sub_opcion_url(sub_opcion), params: { sub_opcion: new_attributes }
        sub_opcion.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sub_opcion" do
        sub_opcion = SubOpcion.create! valid_attributes
        patch sub_opcion_url(sub_opcion), params: { sub_opcion: new_attributes }
        sub_opcion.reload
        expect(response).to redirect_to(sub_opcion_url(sub_opcion))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        sub_opcion = SubOpcion.create! valid_attributes
        patch sub_opcion_url(sub_opcion), params: { sub_opcion: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sub_opcion" do
      sub_opcion = SubOpcion.create! valid_attributes
      expect {
        delete sub_opcion_url(sub_opcion)
      }.to change(SubOpcion, :count).by(-1)
    end

    it "redirects to the sub_opciones list" do
      sub_opcion = SubOpcion.create! valid_attributes
      delete sub_opcion_url(sub_opcion)
      expect(response).to redirect_to(sub_opciones_url)
    end
  end
end
