require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tipo_formularios", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TipoFormulario. As you add validations to TipoFormulario, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TipoFormulario.create! valid_attributes
      get tipo_formularios_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tipo_formulario = TipoFormulario.create! valid_attributes
      get tipo_formulario_url(tipo_formulario)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tipo_formulario_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      tipo_formulario = TipoFormulario.create! valid_attributes
      get edit_tipo_formulario_url(tipo_formulario)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TipoFormulario" do
        expect {
          post tipo_formularios_url, params: { tipo_formulario: valid_attributes }
        }.to change(TipoFormulario, :count).by(1)
      end

      it "redirects to the created tipo_formulario" do
        post tipo_formularios_url, params: { tipo_formulario: valid_attributes }
        expect(response).to redirect_to(tipo_formulario_url(TipoFormulario.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TipoFormulario" do
        expect {
          post tipo_formularios_url, params: { tipo_formulario: invalid_attributes }
        }.to change(TipoFormulario, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tipo_formularios_url, params: { tipo_formulario: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tipo_formulario" do
        tipo_formulario = TipoFormulario.create! valid_attributes
        patch tipo_formulario_url(tipo_formulario), params: { tipo_formulario: new_attributes }
        tipo_formulario.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tipo_formulario" do
        tipo_formulario = TipoFormulario.create! valid_attributes
        patch tipo_formulario_url(tipo_formulario), params: { tipo_formulario: new_attributes }
        tipo_formulario.reload
        expect(response).to redirect_to(tipo_formulario_url(tipo_formulario))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tipo_formulario = TipoFormulario.create! valid_attributes
        patch tipo_formulario_url(tipo_formulario), params: { tipo_formulario: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tipo_formulario" do
      tipo_formulario = TipoFormulario.create! valid_attributes
      expect {
        delete tipo_formulario_url(tipo_formulario)
      }.to change(TipoFormulario, :count).by(-1)
    end

    it "redirects to the tipo_formularios list" do
      tipo_formulario = TipoFormulario.create! valid_attributes
      delete tipo_formulario_url(tipo_formulario)
      expect(response).to redirect_to(tipo_formularios_url)
    end
  end
end
