require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/unidad_medidas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # UnidadMedida. As you add validations to UnidadMedida, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      UnidadMedida.create! valid_attributes
      get unidad_medidas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      unidad_medida = UnidadMedida.create! valid_attributes
      get unidad_medida_url(unidad_medida)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_unidad_medida_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      unidad_medida = UnidadMedida.create! valid_attributes
      get edit_unidad_medida_url(unidad_medida)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new UnidadMedida" do
        expect {
          post unidad_medidas_url, params: { unidad_medida: valid_attributes }
        }.to change(UnidadMedida, :count).by(1)
      end

      it "redirects to the created unidad_medida" do
        post unidad_medidas_url, params: { unidad_medida: valid_attributes }
        expect(response).to redirect_to(unidad_medida_url(UnidadMedida.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new UnidadMedida" do
        expect {
          post unidad_medidas_url, params: { unidad_medida: invalid_attributes }
        }.to change(UnidadMedida, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post unidad_medidas_url, params: { unidad_medida: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested unidad_medida" do
        unidad_medida = UnidadMedida.create! valid_attributes
        patch unidad_medida_url(unidad_medida), params: { unidad_medida: new_attributes }
        unidad_medida.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the unidad_medida" do
        unidad_medida = UnidadMedida.create! valid_attributes
        patch unidad_medida_url(unidad_medida), params: { unidad_medida: new_attributes }
        unidad_medida.reload
        expect(response).to redirect_to(unidad_medida_url(unidad_medida))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        unidad_medida = UnidadMedida.create! valid_attributes
        patch unidad_medida_url(unidad_medida), params: { unidad_medida: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested unidad_medida" do
      unidad_medida = UnidadMedida.create! valid_attributes
      expect {
        delete unidad_medida_url(unidad_medida)
      }.to change(UnidadMedida, :count).by(-1)
    end

    it "redirects to the unidad_medidas list" do
      unidad_medida = UnidadMedida.create! valid_attributes
      delete unidad_medida_url(unidad_medida)
      expect(response).to redirect_to(unidad_medidas_url)
    end
  end
end
